name: "Pull Request Docs Check"
on: 
- pull_request
- workflow_dispatch

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "pip install -r requirements.txt"
        build-command: "sphinx-build -W --keep-going . _build "
